using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: CLSCompliantAttribute(true)]
[assembly: AssemblyTitleAttribute("MutableObject")]
[assembly: AssemblyDescriptionAttribute("The manga-network protocoll")]
[assembly: AssemblyConfigurationAttribute("release")]
[assembly: AssemblyCompanyAttribute("")]
[assembly: AssemblyProductAttribute("MutableObject")]
[assembly: AssemblyCopyrightAttribute("Copyright (C) 2011-2011 Alxandr Productions")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyCultureAttribute("")]
[assembly: AssemblyVersionAttribute("1.1.4273.0")]
[assembly: AssemblyInformationalVersionAttribute("1.1")]

